# Generated by Django 2.2.6 on 2019-11-30 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('file', models.FileField(blank=True, upload_to='calculation/')),
                ('file_name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_date', models.DateTimeField()),
                ('csi', models.FloatField(default=0)),
                ('loyalty', models.FloatField(default=0)),
                ('regress', models.FloatField(default=0)),
                ('one', models.FloatField(default=0)),
                ('two', models.FloatField(default=0)),
                ('three', models.FloatField(default=0)),
                ('four', models.FloatField(default=0)),
                ('five', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
