# Generated by Django 2.2.6 on 2019-12-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='delete_date',
        ),
    ]
