# Generated by Django 2.2.7 on 2019-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_remove_post_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
