# Generated by Django 2.2.7 on 2020-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0005_remove_post_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nps',
            field=models.FloatField(default=0),
        ),
    ]
