# Generated by Django 2.2.7 on 2020-01-25 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_post_barrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='regressb',
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='calculation/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xlsm', 'xltx', 'xltm'])]),
        ),
    ]
