# Generated by Django 2.2.7 on 2021-02-11 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_auto_20200125_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='calculation/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xlsm', 'xltx', 'xltm'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название файла'),
        ),
    ]
